### ISSUE TITLE
The image should be build from github-actions and push to Dockerhub

### ISSUE THREAD

**Issue by Bartixxx32** [AsciiJakob/KissMP-Serverlist#8]
The image should be build from github-actions and push to Dockerhub

(Safety reasons)

(example action script at below)

https://github.com/Bartixxx32/CDA.PL-Folder-Downloader/blob/95808bccf4b3c5ba024e01b1036c8c91bfb07194/.github/workflows/docker-publish.yml#L7

**Comment by AsciiJakob** [comment]
Implemented.
A few months ago, I was using dockerhub's automatic building feature, but that feature is not free anymore.
